// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBksXHXlfxUE1tJRQh4s1O2wcNZhuXDpH0',
    appId: '1:605046739849:web:48a0b9da44d62673b54758',
    messagingSenderId: '605046739849',
    projectId: 'authujikom',
    authDomain: 'authujikom.firebaseapp.com',
    storageBucket: 'authujikom.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAKMbJVCaauihKGD1x0XPZIbrATRxeHOEs',
    appId: '1:605046739849:android:10f50534c5a11d9db54758',
    messagingSenderId: '605046739849',
    projectId: 'authujikom',
    storageBucket: 'authujikom.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAE0izIqETnUEx95YvN0J2ee64wReNXkg',
    appId: '1:605046739849:ios:3987c9370242b37fb54758',
    messagingSenderId: '605046739849',
    projectId: 'authujikom',
    storageBucket: 'authujikom.appspot.com',
    iosBundleId: 'com.example.hyperSnippet',
  );
}
